// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return webProd;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: "AIzaSyAxNgeVftl_KlgFHQD9KyxPmUav7Ps8-1E", // REPLACE WITH YOUR INFO FROM FIREBASE
    authDomain: "pizza-app-4064d.firebaseapp.com", // REPLACE WITH YOUR INFO FROM FIREBASE
    projectId: "pizza-app-4064d", // REPLACE WITH YOUR INFO FROM FIREBASE
    storageBucket: "pizza-app-4064d.firebasestorage.app", // REPLACE WITH YOUR INFO FROM FIREBASE
    messagingSenderId: "20721230687", // REPLACE WITH YOUR INFO FROM FIREBASE
    appId: "1:20721230687:web:7b1dde6b4242f5734e4cea", // REPLACE WITH YOUR INFO FROM FIREBASE
  );
}